In [7]:
import pandas as pd
data_frame = pd.read_csv("data.csv")
data_frame.shape

(64, 88)

In [5]:
data_frame.shape

NameError: name 'data_frame' is not defined

In [6]:
data_frame.shape

NameError: name 'data_frame' is not defined

In [8]:
data_frame.describe()

,number of goals team1,number of goals team2,total attempts team1,total attempts team2,conceded team1,conceded team2,goal inside the penalty area team1,goal inside the penalty area team2,goal outside the penalty area team1,goal outside the penalty area team2,...,penalties scored team1,penalties scored team2,goal preventions team1,goal preventions team2,own goals team1,own goals team2,forced turnovers team1,forced turnovers team2,defensive pressures applied team1,defensive pressures applied team2
count,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,...,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000
mean,1.578125,1.109375,11.140625,11.281250,1.109375,1.578125,1.468750,0.984375,0.093750,0.109375,...,0.140625,0.125000,11.593750,11.359375,0.015625,0.015625,71.968750,70.125000,289.750000,293.265625
std,1.551289,1.055856,4.972519,5.807682,1.055856,1.551289,1.563155,0.999876,0.293785,0.314576,...,0.350382,0.377964,5.911299,4.990045,0.125000,0.125000,14.394629,13.531269,88.406888,80.916230
min,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,38.000000,44.000000,139.000000,141.000000
25%,0.000000,0.000000,8.000000,7.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,7.750000,8.000000,0.000000,0.000000,63.000000,60.250000,229.000000,233.750000
50%,1.000000,1.000000,10.000000,10.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,11.000000,10.000000,0.000000,0.000000,71.000000,72.000000,281.000000,292.500000
75%,2.000000,2.000000,14.000000,14.000000,2.000000,2.000000,2.000000,2.000000,0.000000,0.000000,...,0.000000,0.000000,14.000000,14.000000,0.000000,0.000000,83.500000,79.000000,328.000000,327.500000
max,7.000000,4.000000,25.000000,32.000000,4.000000,7.000000,7.000000,4.000000,1.000000,1.000000,...,1.000000,2.000000,32.000000,26.000000,1.000000,1.000000,101.000000,104.000000,637.000000,585.000000

In [9]:
data_frame.keys

<bound method NDFrame.keys of             team1         team2 possession team1 possession team2  \
0           QATAR       ECUADOR              42%              50%
1         ENGLAND          IRAN              72%              19%
2         SENEGAL   NETHERLANDS              44%              45%
3   UNITED STATES         WALES              51%              39%
4       ARGENTINA  SAUDI ARABIA              64%              24%
..            ...           ...              ...              ...
59        ENGLAND        FRANCE              54%              36%
60      ARGENTINA       CROATIA              34%              54%
61         FRANCE       MOROCCO              34%              55%
62        CROATIA       MOROCCO              45%              45%
63      ARGENTINA        FRANCE              46%              40%

   possession in contest  number of goals team1  number of goals team2  \
0                     8%                      0                      2
1                     9%                      6                      2
2                    11%                      0                      2
3                    10%                      1                      1
4                    12%                      1                      2
..                   ...                    ...                    ...
59                   10%                      1                      2
60                   12%                      3                      0
61                   11%                      2                      0
62                   10%                      2                      1
63                   14%                      3                      3

           date     hour                  category  ...  \
0   20 NOV 2022  17 : 00                   Group A  ...
1   21 NOV 2022  14 : 00                   Group B  ...
2   21 NOV 2022  17 : 00                   Group A  ...
3   21 NOV 2022  20 : 00                   Group B  ...
4   22 NOV 2022  11 : 00                   Group C  ...
..          ...      ...                       ...  ...
59  10 DEC 2022  20 : 00             Quarter-final  ...
60  13 DEC 2022  20 : 00                Semi-final  ...
61  14 DEC 2022  20 : 00                Semi-final  ...
62  17 DEC 2022  16 : 00  Play-off for third place  ...
63  18 DEC 2022  16 : 00                     Final  ...

    penalties scored team1  penalties scored team2  goal preventions team1  \
0                        0                       1                       6
1                        0                       1                       8
2                        0                       0                       9
3                        0                       1                       7
4                        1                       0                       4
..                     ...                     ...                     ...
59                       1                       0                       9
60                       1                       0                      12
61                       0                       0                      13
62                       0                       0                       7
63                       1                       2                      11

    goal preventions team2  own goals team1  own goals team2  \
0                        5                0                0
1                       13                0                0
2                       15                0                0
3                        7                0                0
4                       14                0                0
..                     ...              ...              ...
59                      15                0                0
60                      10                0                0
61                      14                0                0
62                      14                0                0
63                      21                0                0

    forced turnovers team1  forced turnovers team2  \
0                       52                      72
1                       63                      72
2                       63                      73
3                       81                      72
4                       65                      80
..                     ...                     ...
59                      49                      54
60                      85                      63
61                      72                      47
62                      75                      72
63                      87                     104

    defensive pressures applied team1  defensive pressures applied team2
0                                 256                                279
1                                 139                                416
2                                 263                                251
3                                 242                                292
4                                 163                                361
..                                ...                                ...
59                                193                                308
60                                321                                260
61                                328                                218
62                                288                                277
63                                280                                409

[64 rows x 88 columns]>

In [10]:
data_frame.values

array([['QATAR', 'ECUADOR', '42%', ..., 72, 256, 279],
       ['ENGLAND', 'IRAN', '72%', ..., 72, 139, 416],
       ['SENEGAL', 'NETHERLANDS', '44%', ..., 73, 263, 251],
       ...,
       ['FRANCE', 'MOROCCO', '34%', ..., 47, 328, 218],
       ['CROATIA', 'MOROCCO', '45%', ..., 72, 288, 277],
       ['ARGENTINA', 'FRANCE', '46%', ..., 104, 280, 409]], dtype=object)

In [11]:
data_frame.keys()

Index(['team1', 'team2', 'possession team1', 'possession team2',
       'possession in contest', 'number of goals team1',
       'number of goals team2', 'date', 'hour', 'category',
       'total attempts team1', 'total attempts team2', 'conceded team1',
       'conceded team2', 'goal inside the penalty area team1',
       'goal inside the penalty area team2',
       'goal outside the penalty area team1',
       'goal outside the penalty area team2', 'assists team1', 'assists team2',
       'on target attempts team1', 'on target attempts team2',
       'off target attempts team1', 'off target attempts team2',
       'attempts inside the penalty area team1',
       'attempts inside the penalty area  team2',
       'attempts outside the penalty area  team1',
       'attempts outside the penalty area  team2', 'left channel team1',
       'left channel team2', 'left inside channel team1',
       'left inside channel team2', 'central channel team1',
       'central channel team2', 'right inside channel team1',
       'right inside channel team2', 'right channel team1',
       'right channel team2', 'total offers to receive team1',
       'total offers to receive team2', 'inbehind offers to receive team1',
       'inbehind offers to receive team2', 'inbetween offers to receive team1',
       'inbetween offers to receive team2', 'infront offers to receive team1',
       'infront offers to receive team2',
       'receptions between midfield and defensive lines team1',
       'receptions between midfield and defensive lines team2',
       'attempted line breaks team1', 'attempted line breaks team2',
       'completed line breaksteam1', 'completed line breaks team2',
       'attempted defensive line breaks team1',
       'attempted defensive line breaks team2',
       'completed defensive line breaksteam1',
       'completed defensive line breaks team2', 'yellow cards team1',
       'yellow cards team2', 'red cards team1', 'red cards team2',
       'fouls against team1', 'fouls against team2', 'offsides team1',
       'offsides team2', 'passes team1', 'passes team2',
       'passes completed team1', 'passes completed team2', 'crosses team1',
       'crosses team2', 'crosses completed team1', 'crosses completed team2',
       'switches of play completed team1', 'switches of play completed team2',
       'corners team1', 'corners team2', 'free kicks team1',
       'free kicks team2', 'penalties scored team1', 'penalties scored team2',
       'goal preventions team1', 'goal preventions team2', 'own goals team1',
       'own goals team2', 'forced turnovers team1', 'forced turnovers team2',
       'defensive pressures applied team1',
       'defensive pressures applied team2'],
      dtype='object')

In [12]:
data_frame

,team1,team2,possession team1,possession team2,possession in contest,number of goals team1,number of goals team2,date,hour,category,...,penalties scored team1,penalties scored team2,goal preventions team1,goal preventions team2,own goals team1,own goals team2,forced turnovers team1,forced turnovers team2,defensive pressures applied team1,defensive pressures applied team2
0,QATAR,ECUADOR,42%,50%,8%,0,2,20 NOV 2022,17 : 00,Group A,...,0,1,6,5,0,0,52,72,256,279
1,ENGLAND,IRAN,72%,19%,9%,6,2,21 NOV 2022,14 : 00,Group B,...,0,1,8,13,0,0,63,72,139,416
2,SENEGAL,NETHERLANDS,44%,45%,11%,0,2,21 NOV 2022,17 : 00,Group A,...,0,0,9,15,0,0,63,73,263,251
3,UNITED STATES,WALES,51%,39%,10%,1,1,21 NOV 2022,20 : 00,Group B,...,0,1,7,7,0,0,81,72,242,292
4,ARGENTINA,SAUDI ARABIA,64%,24%,12%,1,2,22 NOV 2022,11 : 00,Group C,...,1,0,4,14,0,0,65,80,163,361
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,ENGLAND,FRANCE,54%,36%,10%,1,2,10 DEC 2022,20 : 00,Quarter-final,...,1,0,9,15,0,0,49,54,193,308
60,ARGENTINA,CROATIA,34%,54%,12%,3,0,13 DEC 2022,20 : 00,Semi-final,...,1,0,12,10,0,0,85,63,321,260
61,FRANCE,MOROCCO,34%,55%,11%,2,0,14 DEC 2022,20 : 00,Semi-final,...,0,0,13,14,0,0,72,47,328,218
62,CROATIA,MOROCCO,45%,45%,10%,2,1,17 DEC 2022,16 : 00,Play-off for third place,...,0,0,7,14,0,0,75,72,288,277
63,ARGENTINA,FRANCE,46%,40%,14%,3,3,18 DEC 2022,16 : 00,Final,...,1,2,11,21,0,0,87,104,280,409